### ISSUE TITLE
We need a way to OCR the entire screen

### ISSUE THREAD

**Issue by Simon818** [nvaccess/nvda-ocr#1]
I was working with a particularly nasty application that starts with a Team and ends with a Speak, and realized that I can't get past the license agreement page because NVDA is not aware that the bottom part of the screen is part of the same window. There doesn't seem to be a way to OCR the entire screen, just the active window, and particularly when that window consists of a bunch of buttons with no proper parent, it's difficult to define boundaries. I'm probably missing something obvious, but right now I'm stuck, and it occurs to me that this is a problem which could apply to quite a lot of places, so hopefully this is the right place for it.

**Comment by jcsteh** [comment]
You should be able to use object navigation to get to the window (by moving to the containing object a few times), which covers the full screen. The command OCRs the review object, which will generally be the focus initially until you navigate with object navigation.

**Comment by Simon818** [comment]
The problem is that in this case, and a few other cases I've seen, it 
didn't seem to read the entire window contents (as though NVDA assumed 
the window to be smaller than it actually was). It got about halfway 
down the agreement and then stopped. I know this was not a resolution 
problem because I was able to make it read a different part of the 
screen by focusing an obscured and larger window that was behind the 
foreground one.

**Comment by jcsteh** [comment]
Did you move to the top most containing object (just beneath the desktop)?

There are a few possibilities. One is that Tesseract just couldn't OCR 
that part of the text at all. It certainly wouldn't be the first time. 
:) The other is that the location reported by the window was incorrect 
for some reason. It might help if you can give me the dev info for the 
review object you tried to OCR.
