### ISSUE TITLE
Add support for configuration profiles

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda-ocr#2]
Use cases:
Set different languages for the add-on, that can be used in different programs or situations.
technical: Manage config from the central system.
Thanks.

**Comment by feerrenrut** [comment]
I believe this is resolved with #6093

**Comment by feerrenrut** [comment]
My mistake, re-opening the issue.

**Comment by lukaszgo1** [comment]
@nvdaes  In my fork https://github.com/lukaszgo1/nvda-ocr I've started using config.conf to store configuration. Unless there is something which is not implemented in your opinion you can close this issue I guess.

**Comment by nvdaes** [comment]
Thanks, I will close this.
